TRAIN_TEST_SPLIT: 0.1

BATCH_SIZE: 32
LEARNING_RATE: 1e-5
EPOCHS: 2
INPUT_DIM: 4
OUTPUT_DIM: 2

DATA:
  MAX_SEQ_LENGTH: 512

MODEL_PARAMS:
  EMBED_DIM: 64
  NUM_HEADS: 4
  NUM_LAYERS: 2
  FFN_DIM: 128
  DROPOUT: 0.0